#!/usr/bin/with-contenv bash

# set capabilities for domoticz binary
setcap cap_net_raw=+eip /var/lib/domoticz/domoticz

exec \
    s6-setuidgid domoticz /var/lib/domoticz/domoticz \
        -userdata /config/ \
        -dbase /config/domoticz.db \
        -www 8080 \
        -sslwww 8443
        -sslcert /var/lib/domoticz/server_cert.pem