#!/usr/bin/with-contenv bash

# add domoticz user with uid and gid from command line when given
if [ -z "$PUID"  ] && [ -z "$GUID" ]; then
    useradd domoticz -M -d /var/lib/domoticz
else
    groupadd domoticz -g $PGID
    useradd domoticz -M -d /var/lib/domoticz -u $PUID -g $PGID
fi

# allow domitcz user access to dialout (serial connections)
usermod -a -G dialout domoticz

# copy default scripts from install
[[ ! -e /config/scripts ]] && \
	cp -R /var/lib/domoticz/scripts /config/

# copy db if needed
[[ ! -e /config/domoticz.db ]] && \
	cp /var/lib/domoticz/domoticz.db /config/

# copy .ssh directory if exists
[[ -e /config/.ssh ]] && \
	cp -R /config/.ssh /var/lib/domoticz/
	chmod 700 /var/lib/domoticz/.ssh
	chmod 600 /var/lib/domoticz/.ssh/id_rsa*

# set permissions for /config
chown -R domoticz:domoticz \
	/config \
	/tmp \
	/var/lib/domoticz
chmod -R 764 \
	/config





